
export const ActionTypes = {
    SET_ARTICLES_START:'SET_ARTICLES_START',
    SET_ARTICLES :'SET_ARTICLES',
    SELECTED_ARTICLE_START: 'SELECTED_ARTICLE_START',
    SELECTED_ARTICLE : 'SELECTED_ARTICLE',
    REMOVE_SELECTED_ARTICLE :' REMOVE_SELECTED_ARTICLE',
    SELECTED_CATEGORY_START :'SELECTED_CATEGORY_START',
    SELECTED_CATEGORY :'SELECTED_CATEGORY',
    REMOVE_SELECTED_CATEGORY : 'REMOVE_SELECTED_CATEGORY'

}


